[tool.poetry]
name = "lastricks"
version = "0.1.3"
description = "A few LAS manipulations"
authors = ["Elie-Alban LESCOUT <elie-alban.lescout@eurosense.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pytest = "^6.2"
laspy =  "^2.0"
laszip = "^0.1"
rasterio = "^1.2"
numpy = "^1.22"
Shapely = "^1.8"
pathos = "^0.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
filterwarnings = [
    "error",
    "ignore::UserWarning"
]
